name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Run the job on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm ci # Install project dependencies (e.g., for a React, Vue, or static site generator)

      - name: Build project
        run: npm run build # Run your project's build command (e.g., 'npm run build' for many front-end projects)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' # Only deploy if the push is to the 'main' branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub Token automatically provided by GitHub Actions
          publish_dir: ./build # The directory containing your built files (e.g., 'build', 'public', 'dist')
          # You can also specify the target branch for GitHub Pages, e.g., 'gh-pages'
          # publish_branch: gh-pages
